name: Push GitHub directory to Azure DevOps repository

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  sync-to-azure:
    runs-on: windows-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

            - name: Run sync script to Azure DevOps
        shell: pwsh
        env:
          AZUREPAT: ${{ secrets.AZUREPAT }}
          AZUSERNAME: ${{ secrets.AZUREUSERNAME }}
          AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
          AZORG: ${{ secrets.AZORG }}
        run: |
          pwsh -File "/.github/workflows/script/commit.ps1"
<<<<<<< HEAD
=======

>>>>>>> fb934ac5607f378aaa70e87d221058829d960b2c
