name: Push GitHub directory to Azure DevOps repository

on:
  push:
    branches:
      - '*'  # Triggers on all branches
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  sync-to-azure:
    runs-on: windows-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Run sync script to Azure DevOps
        shell: pwsh
        env:
          AZUREPAT: ${{ secrets.AZUREPAT }}
          AZUSERNAME: ${{ secrets.AZUREUSERNAME }}
          AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
          AZORG: ${{ secrets.AZORG }}
        run: |
          .\.github\workflows\script\commit.ps1
